// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: job.sql

package ent

import (
	"context"
)

const waitForJob = `-- name: WaitForJob :one
SELECT sys.wait_for_job($1::TEXT)::BOOLEAN AS ok
`

type WaitForJobParams struct {
	JobID string `db:"job_id" json:"job_id"`
}

// Waits for a job to complete by its ID.
func (q *Queries) WaitForJob(ctx context.Context, arg *WaitForJobParams) (bool, error) {
	row := q.db.QueryRow(ctx, waitForJob, arg.JobID)
	var ok bool
	err := row.Scan(&ok)
	return ok, err
}
