// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package ent

type ExecInsertRevisionParamsConverterImpl struct{}

func (c *ExecInsertRevisionParamsConverterImpl) SetFromRevision(target *ExecInsertRevisionParams, source *Revision) {
	if source != nil {
		target.ID = source.ID
		target.Description = source.Description
		target.ExecutedAt = source.ExecutedAt
		target.ExecutionTime = source.ExecutionTime
	}
}

type GetRevisionParamsConverterImpl struct{}

func (c *GetRevisionParamsConverterImpl) SetFromRevision(target *GetRevisionParams, source *Revision) {
	if source != nil {
		target.ID = source.ID
	}
}

type InsertRevisionParamsConverterImpl struct{}

func (c *InsertRevisionParamsConverterImpl) SetFromRevision(target *InsertRevisionParams, source *Revision) {
	if source != nil {
		target.ID = source.ID
		target.Description = source.Description
		target.ExecutedAt = source.ExecutedAt
		target.ExecutionTime = source.ExecutionTime
	}
}
