// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package ent

import (
	"context"
)

type Querier interface {
	// Creates a table named 'aurora_schema_revisions' with the following columns:
	CreateTableRevisions(ctx context.Context) error
	// Inserts a row into the table 'aurora_schema_revisions' with option ':exec'
	ExecInsertRevision(ctx context.Context, arg *ExecInsertRevisionParams) error
	// Retrieves a row from the table 'aurora_schema_revisions' with option ':one'
	GetRevision(ctx context.Context, arg *GetRevisionParams) (*Revision, error)
	// Inserts a row into the table 'aurora_schema_revisions' with option ':one'
	InsertRevision(ctx context.Context, arg *InsertRevisionParams) (*Revision, error)
	// Retrieves a list of rows from the table 'aurora_schema_revisions' with option ':many'
	ListRevisions(ctx context.Context, arg *ListRevisionsParams) ([]*Revision, error)
	// Waits for a job to complete by its ID.
	WaitForJob(ctx context.Context, arg *WaitForJobParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
