services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - ..:/home/vscode/workspace:cached
      - $HOME/go/pkg:/home/vscode/go/pkg
  db:
    image: postgres:17.2-bookworm
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      # required by the pg_isready
      PGUSER: vscode
      PGHOST: localhost
      PGDATABASE: aurora
      # required by the pg_docker
      POSTGRES_DB: aurora
      POSTGRES_USER: vscode
      POSTGRES_HOSTNAME: localhost
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    network_mode: service:workspace
volumes:
  postgres-data:
